set(_CATKIN_CURRENT_PACKAGE "wanji_msgs")
set(wanji_msgs_VERSION "1.2.0")
set(wanji_msgs_MAINTAINER "Jack O'Quin <jack.oquin@gmail.com>")
set(wanji_msgs_PACKAGE_FORMAT "1")
set(wanji_msgs_BUILD_DEPENDS "message_generation" "std_msgs")
set(wanji_msgs_BUILD_EXPORT_DEPENDS "message_runtime" "std_msgs")
set(wanji_msgs_BUILDTOOL_DEPENDS "catkin")
set(wanji_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(wanji_msgs_EXEC_DEPENDS "message_runtime" "std_msgs")
set(wanji_msgs_RUN_DEPENDS "message_runtime" "std_msgs")
set(wanji_msgs_TEST_DEPENDS )
set(wanji_msgs_DOC_DEPENDS )
set(wanji_msgs_DEPRECATED "")